# action.yaml
name: 'GitHub Actions ChatGPT PR Reviewer'
description: 'A Github Action that uses ChatGPT to review PRs'
inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
    default: ''
  openai_model:
    description: 'OpenAI Model'
    required: false
    default: 'gpt-3.5-turbo'
  openai_temperature:
    description: 'Temperature fo randomness, 0 is more conservative and 1 is more creative.'
    required: false
    default: '0.5'
  openai_max_tokens:
    description: 'The maximum number of tokens to generate in the completion.'
    required: false
    default: '2048'
  github_token:
    description: 'Github API Key'
    required: true
    default: ''
  github_pr_id:
    description: 'Github PR ID'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      shell: bash
      run: pip install "openai==0.27.*" "PyGithub~=1.57" "requests~=2.28.2"

    - name: Pass Inputs to Shell
      shell: bash
      run: |
          echo "OPENAI_API_KEY=${{ inputs.openai_api_key }}" >> $GITHUB_ENV
          echo "OPENAI_MODEL=${{ inputs.openai_model }}" >> $GITHUB_ENV
          echo "OPENAI_TEMPERATURE=${{ inputs.openai_temperature }}" >> $GITHUB_ENV
          echo "OPENAI_MAX_TOKENS=${{ inputs.openai_max_tokens }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
          echo "GITHUB_PR_ID=${{ inputs.github_pr_id }}" >> $GITHUB_ENV

    - name: GitHub ChatGPT PR Reviewer
      shell: bash
      id: run-reviewer
      run: python src/gha_gpt_pr_reviewer.py
