# action.yaml
name: 'GitHub Actions ChatGPT PR Reviewer'
description: 'A Github Action that uses ChatGPT to review PRs'
inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
    default: ''
  openai_model:
    description: 'OpenAI Model'
    required: false
    default: 'gpt-4-1106-preview'
  openai_temperature:
    description: 'Temperature fo randomness, 0 is more conservative and 1 is more creative.'
    required: false
    default: '0.5'
  openai_max_tokens:
    description: 'The maximum number of tokens to generate in the completion.'
    required: false
    default: '2048'
  openai_extra_criteria:
    description: 'Add extra criteria for the PR reviewer. Split your criteria with `;`'
    required: false
    default: ''
  github_token:
    description: 'Github API Key'
    required: true
    default: ''
  github_pr_id:
    description: 'Github PR ID'
    required: true
    default: ''

branding:
  icon: check-circle
  color: green

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.openai_model }}
    - ${{ inputs.openai_temperature }}
    - ${{ inputs.openai_max_tokens }}
    - ${{ inputs.openai_extra_criteria }}
    - ${{ inputs.github_token }}
    - ${{ inputs.github_pr_id }}
