# action.yml (composite)
name: GitHub Actions ChatGPT PR Reviewer
description: Review PRs with OpenAI
branding: { icon: check-circle, color: green }

inputs:
  openai_api_key: { description: "OpenAI API Key", required: true }
  openai_model:
    { description: "OpenAI Model", required: false, default: "gpt-4o-mini" }
  openai_temperature:
    { description: "Temperature", required: false, default: "0.0" }
  openai_max_tokens:
    { description: "Max tokens", required: false, default: "8000" }
  openai_extra_criteria:
    {
      description: "Extra criteria (; separated)",
      required: false,
      default: "",
    }
  github_token: { description: "GitHub token", required: true }
  github_pr_id: { description: "PR number", required: true }
  openai_reasoning:
    description: "Use reasoning mode (on|off|auto). Auto detects by model name."
    required: false
    default: "auto"
  openai_reasoning_effort:
    description: "Reasoning effort if supported (low|medium|high)."
    required: false
    default: "medium"
  openai_max_completion_tokens:
    description: |
      Max completion tokens (reasoning models / Chat API).
      Also used as max_output_tokens for Responses API.
    required: false
    default: "2048"
  exclude_path:
    description: "Glob patterns to exclude (comma/; or newline separated)"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with: { python-version: "3.13" }

    - name: Install deps
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r "$GITHUB_ACTION_PATH/requirements.txt"

    - name: Run reviewer
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        OPENAI_MODEL: ${{ inputs.openai_model }}
        OPENAI_TEMPERATURE: ${{ inputs.openai_temperature }}
        OPENAI_MAX_TOKENS: ${{ inputs.openai_max_tokens }}
        OPENAI_EXTRA_CRITERIA: ${{ inputs.openai_extra_criteria }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_PR_ID: ${{ inputs.github_pr_id }}
        OPENAI_REASONING: ${{ inputs.openai_reasoning }}
        OPENAI_REASONING_EFFORT: ${{ inputs.openai_reasoning_effort }}
        OPENAI_MAX_COMPLETION_TOKENS: ${{ inputs.openai_max_completion_tokens }}
        EXCLUDE_PATH: ${{ inputs.exclude_path }}
      run: python "$GITHUB_ACTION_PATH/main.py"
